master
vertx-howtos/executable-jar-docker-howto pull request #1
Opened 2021-03-16 14:53 UTC by tsegismont

Initial version of the executable-jar-docker-howto

2021-03-16 21:52 UTC, jponge requested changes
Minor remarks, otherwise a solid how-to!

2021-03-16 21:52 UTC, jponge commented on docker-gradle/Dockerfile
> +FROM openjdk:11-slim
How about using https://hub.docker.com/_/adoptopenjdk ?

2021-03-16 21:52 UTC, jponge commented on docker-gradle/Dockerfile
> +CMD ["exec java -jar $APP_FILE"]
```suggestion
CMD ["exec", "java", "-jar", "$APP_FILE"]
```

2021-03-16 21:52 UTC, jponge commented on docker-maven/Dockerfile
> +CMD ["exec java -jar $APP_FILE"]
Same remark here

2021-03-17 11:09 UTC, tsegismont commented
@jponge PTAL

We must use the string for `CMD` because it the argument for the `ENTRY_POINT` (`bash -c`)

2021-03-17 12:02 UTC, jponge commented
Good catch indeed

2021-03-17 12:02 UTC, jponge approved these changes

2021-03-17 13:10 UTC, merged